model:
  name: "PrunaAI/IlyaGusev-saiga_mistral_7b_merged-AWQ-4bit-smashed"
  quantization: "awq_marlin"
  gpu_memory_utilization: 0.8
  dtype: "auto"
  max_model_len: 8000

paths:
  samples: "samples.yaml"
  courses: "courses.yaml"
  about_realit: "about_realit.txt"
  locations: "locations.yaml"
  system_prompt: "system_prompt.txt"  

logging:
  level: INFO
  format: "%(asctime)s %(levelname)s %(message)s"
  filename: "app.log"
  filemode: "a"

uvicorn:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 1
  log_level: "info"

api_keys:
  - "apikey1" # Поменять на свой ключ в Проде

cors:
  allow_origins:
    - "*"   # или список доменов, например https://it-schools.org/ https://s-it-schools.org/
