paths:
  model: "configs/model.yaml"
  samples: "configs/samples.yaml"
  system_prompt: "configs/system_prompt.txt"  
  courses: "configs/courses.yaml"
  locations: "configs/locations.yaml"
  teachers: "configs/teachers.yaml"

uvicorn:
  host: "0.0.0.0"
  port: 8000
  reload: False
  workers: 1
  log_level: "info"

api_keys:
  - "apikey1" # Поменять на свой ключ в Проде

cors:
  allow_origins:
    - "*"   # или список доменов, например https://it-schools.org/ https://s-it-schools.org/
