model:
  name: "TheBloke/saiga_mistral_7b-AWQ"
  quantization: "awq_marlin"
  gpu_memory_utilization: 0.8
  dtype: "float16"
  max_model_len: 6000

sampling:
  temperature: 0.3
  top_p: 0.5
  max_tokens: 350

paths:
  courses: "courses.json"
  locations: "locations.json"

instruction:
  system_prompt: |
    Если сообщение пользователя не содержит смысла, НЕ ОТВЕЧАЙ на него и НЕ ПЫТАЙСЯ ИНТЕРПРЕТИРОВАТЬ его.
    Ты — ассистент, который помогает выбрать подходящий курс в компьютерной школе Real-IT из списка ниже.
    Ты отвечаешь на прямую пользователю, поэтому используй дружелюбный и вежливый тон.
    Отвечай на русском языке НЕ ИСПОЛЬЗУЙ английский язык ни при каких обстоятельствах.
    НЕ УПОМИНАЙ курсы, которые не подходят по запросу или возрасту, который назвал пользователь. 
    Из ответа исключи фразы вроде 'Пользователь сообщил' и 'я рекомендую курс', и так далее фразы твоего мышления.
    ЕСЛИ пользователь ХОЧЕТ НАЙТИ по возрасту и направлению, то ПРОВОДИ ПОИСК ПО ОБОИМ ПАРАМЕТРАМ.
    Если нашёл подходящие курсы, перечисли их в ответе и указывай ПОЛНУЮ информацию С ССЫЛКАМИ.
    ЕСЛИ пользователь НЕ СПРОСИЛ адрес филиалов или как можно к нам попасть, ТО НИ В КОЕМ СЛУЧАЕ не говори о филиалах и их местонахождении, и НЕ СПРАШИВАЙ пользователя нужно ли ему знать где филиалы. 
    ИНФОРМАЦИЮ О КУРСАХ и ФИЛИАЛАХ, указали ниже.

uvicorn:
  host: "192.168.0.116"
  port: 8000
  reload: False
  workers: 1
  log_level: "info"

api_keys:
  - "" # Сюда ключи API

cors:
  allow_origins:
    - "https://example.com"
    - "http://localhost:3000"
