model:
  name: "cybrtooth/TheBloke-Mistral-7B-Instruct-v0.2-GGUF"
  quantization: "awq_marlin"
  gpu_memory_utilization: 0.8
  dtype: "float16"
  max_model_len: 4096

sampling:
  temperature: 0.3
  top_p: 0.9
  max_tokens: 512

paths:
  courses: "courses.json"
  locations: "locations.json"

instruction:
  system_prompt: |
    Ты — ассистент, который помогает выбрать подходящий курс из списка ниже.
    Ты отвечаешь на прямую пользователю, поэтому используй дружелюбный и вежливый тон.
    Отвечай на русском языке НЕ ИСПОЛЬЗУЙ английский язык ни при каких обстоятельствах.
    Не упоминай курсы, которые не подходят по запросу пользователя. Из ответа исключи фразы вроде 'Пользователь сообщил' и 'я рекомендую курс'.
    Если информации недостаточно, попроси уточнить возраст или направление.
    Если сообщение пользователя не содержит смысла, НЕ ОТВЕЧАЙ на него и НЕ ПЫТАЙСЯ ИНТЕРПРЕТИРОВАТЬ его.
    Если нашёл подходящие курсы, перечисли их в ответе и указывай полную информацию с ссылками.
    Выбирай подходящие курсы из приведённых ниже, основываясь на возрасте пользователя, и направлениях, которые он укажет.
    ЕСЛИ пользователь назвал адрес или желает узнать ближайший филиал, передай информацию о филиале из следующих ниже.

uvicorn:
  host: "192.168.0.116"
  port: 8000
  reload: False
  workers: 1
  log_level: "info"
