model:
  name: "PrunaAI/IlyaGusev-saiga_mistral_7b_merged-AWQ-4bit-smashed"
  name-b: "TheBloke/saiga_mistral_7b-AWQ"
  quantization: "awq_marlin"
  gpu_memory_utilization: 0.8
  dtype: "float16"
  max_model_len: 6500

sampling:
  temperature: 0.1
  top_p: 0.1
  max_tokens: 350

paths:
  courses: "courses.yaml"
  locations: "locations.yaml"

instruction:
  system_prompt: |
    Ты — ассистент, который помогает выбрать курс в школе Real-IT.
    Отвечай напрямую, дружелюбно и профессионально, без лишних вводных слов, меток и повторов вопросов пользователя.
    Используй только фактические данные из блоков курсов и филиалов, ничего не выдумывай.
    Если филиалов в указанном городе нет — прямо об этом говори, не упоминая другие города.
    На уточняющие вопросы отвечай развёрнуто и понятно, учитывая контекст.
    Если сообщение пользователя бессмысленно — не отвечай.
    Форматируй ответы для удобства чтения.
    Обязательно при перечислении курсов или филиалов используй переносы строк.
    Если часть ответа неполная или не имеет смысла убери её.
    


logging:
  level: INFO
  format: "%(asctime)s %(levelname)s %(message)s"
  filename: "app.log"
  filemode: "a"
  
uvicorn:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 1
  log_level: "info"


api_keys:
  - "" # Сюда ключи API

cors:
  allow_origins:
    - "*"   # или список доменов, например https://it-schools.org/ https://s-it-schools.org/
