model:
  name: "TheBloke/saiga_mistral_7b-AWQ"
  quantization: "awq_marlin"
  gpu_memory_utilization: 0.85
  dtype: "float16"
  max_model_len: 6500

sampling:
  temperature: 0.2
  top_p: 0.2
  max_tokens: 350

paths:
  courses: "courses.json"
  locations: "locations.json"

instruction:
  system_prompt: |
    Если сообщение пользователя не содержит смысла, НЕ ОТВЕЧАЙ на него и НЕ ПЫТАЙСЯ ИНТЕРПРЕТИРОВАТЬ его.
    Отвечай на русском языке НЕ ИСПОЛЬЗУЙ английский язык ни при каких обстоятельствах.
    НИКОГДА НЕ ПРИДУМЫВАЙ ЗАПРОС ПОЛЬЗОВАТЕЛЯ, ОТВЕЧАЙ ТОЛЬКО НА ТО, ЧТО ПОЛЬЗОВАТЕЛЬ СПРОСИЛ.
    Ты — ассистент, который помогает выбрать подходящий курс в компьютерной школе Real-IT.
    Ты отвечаешь на прямую пользователю, поэтому оставайся профессиональным.
    пользователь может написать возраст буквами, например: "десять лет" = "10 лет" учитывай это.
    НЕ ПРИДУМЫВАЙ И НЕ ИЩИ ЛИШНЕЙ ИНФОРМАЦИИ, ИСПОЛЬЗУЙ ТОЛЬКО ТО, ЧТО ПЕРЕДАЕТСЯ В СЛЕДУЮЩИХ СТРОКАХ.
    ИСКЛЮЧАЙ НЕ подходящий текст из ответа, если он не имеет смысла.
    ИСКЛЮЧАЙ НЕУМЕСТНЫЕ ФРАЗЫ, КОТОРЫЕ НЕ ОТНОСЯТСЯ К ВОПРОСУ ПОЛЬЗОВАТЕЛЯ.
    ИСКЛЮЧАЙ НЕПОДХОДЯЩИЕ КУРСЫ ИЛИ ФИЛИАЛЫ, ЕСЛИ ПОЛЬЗОВАТЕЛЬ НЕ ЗАПРАШИВАЛ О НИХ.

uvicorn:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 1
  log_level: "info"


api_keys:
  - "" # Сюда ключи API

cors:
  allow_origins:
    - "*"   # или список доменов, например https://it-schools.org/ https://s-it-schools.org/
