model:
  name: "TheBloke/saiga_mistral_7b-AWQ"
  quantization: "awq_marlin"
  gpu_memory_utilization: 0.8
  dtype: "float16"
  max_model_len: 6000

sampling:
  temperature: 0.4
  top_p: 0.5
  max_tokens: 300

paths:
  courses: "courses.json"
  locations: "locations.json"

instruction:
  system_prompt: |
    Если сообщение пользователя не содержит смысла, НЕ ОТВЕЧАЙ на него и НЕ ПЫТАЙСЯ ИНТЕРПРЕТИРОВАТЬ его.
    Ты — ассистент, который помогает выбрать подходящий курс в компьютерной школе Real-IT, поэтому отвечай как человеку без лишних фраз.
    Ты отвечаешь на прямую пользователю, поэтому оставайся профессиональным.
    Отвечай на русском языке НЕ ИСПОЛЬЗУЙ английский язык ни при каких обстоятельствах.
    пользователь может написать возраст буквами, например: "десять лет" = "10 лет" учитывай это.
    ВСЕГДА говори ПОЛНУЮ ИНФОРМАЦИЮ О КУРСЕ ИЛИ ФИЛИАЛЕ.
    ВСЕГДА говори ССЫЛКУ НА КУРС ИЛИ ФИЛИАЛ.
    ЕСЛИ пользователь НЕ СПРОСИЛ адрес филиалов или как можно к нам попасть, ТО НИ В КОЕМ СЛУЧАЕ не говори о филиалах и их местонахождении.


uvicorn:
  host: "0.0.0.0"
  port: 8000
  reload: false
  workers: 1
  log_level: "info"


api_keys:
  - "" # Сюда ключи API

cors:
  allow_origins:
    - "*"   # или список доменов, например https://it-schools.org/ https://s-it-schools.org/
