курсы:
  - курс: Курсы для дошкольников
    направление: дошкольное
    диапазон возраста: от 3 до 7 лет
    описание: >
      Занятия направлены на формирование познавательного интереса,
      памяти, внимания, интеллекта.
    ссылка: https://it-schools.org/year/course/preschool/

  - курс: Робототехника
    направление: роботы
    диапазон возраста: от 7 до 16 лет
    описание: >
      На уроках робототехники в нашей школе дети осваивают базовую механику,
      основы электроники и программирования микропроцессоров.
      Обучение проходит 5 курсов.
    ссылка: https://it-schools.org/year/course/robotics/

  - курс: Информатика для школы
    направление: информатика
    диапазон возраста: от 8 до 14 лет
    описание: >
      На этом курсе обучающиеся изучают устройство компьютера,
      базовое программное обеспечение, основы работы с компьютером.
    ссылка: https://it-schools.org/year/course/informatics/

  - курс: Теория информатики
    направление: информатика
    диапазон возраста: от 10 до 16 лет
    описание: >
      Изучение теории по дисциплине «Информатика» и решение большого
      количества задач. Запись возможна только после прохождения
      первого курса Python или C++.
    ссылка: https://it-schools.org/year/course/theory-Informatics/

  - курс: Спортивное программирование
    направление: программирование
    диапазон возраста: от 12 до 15 лет
    описание: >
      Основы программирования через соревновательную деятельность.
      Обучение проходит 3 курса.
    ссылка: https://it-schools.org/year/course/sport-prog/

  - курс: Основы программирования
    направление: программирование
    диапазон возраста: от 9 до 12 лет
    описание: >
      Изучение базовых принципов алгоритмизации и развитие логического
      мышления. Обучение проходит 2 курса.
    ссылка: https://it-schools.org/year/course/programming-begin/

  - курс: WEB-разработка
    направление: Web
    диапазон возраста: от 9 до 17 лет
    описание: >
      Изучение вёрстки сайтов и сопутствующих технологий.
      Обучение проходит 4 курса, есть возможность закрыть экстерном.
    ссылка: https://it-schools.org/year/course/web/

  - курс: Компьютерная графика
    направление: Дизайн
    диапазон возраста: от 8 до 17 лет
    описание: >
      Работа с разными типами графики: векторная, растровая и трёхмерная.
      Обучение проходит 5 курсов.
    ссылка: https://it-schools.org/year/course/graphics/

  - курс: Программирование Python
    направление: программирование
    диапазон возраста: от 9 до 18 лет
    описание: >
      Изучение языка Python: от лёгких приложений до ООП
      и работы с базами данных. Обучение проходит 4 курса.
    ссылка: https://it-schools.org/year/course/programming-python/

  - курс: Программирование C++
    направление: программирование
    диапазон возраста: от 10 до 18 лет
    описание: >
      Изучение языка C++: от простых приложений до создания
      мессенджеров и онлайн-игр. Обучение проходит 4 курса.
    ссылка: https://it-schools.org/year/course/programming-cpp/

  - курс: Нейронные сети
    направление: программирование
    диапазон возраста: от 14 до 18 лет
    описание: >
      Изучение основ нейронных сетей и их применения.
      Обучение проходит 2 курса.
    ссылка: https://it-schools.org/year/course/neuron/

  - курс: Программирование Processing
    направление: программирование
    диапазон возраста: от 12 до 18 лет
    описание: >
      Изучение основ инструмента processing,
      создание с помощью него собственной игры.
    ссылка: https://it-schools.org/year/course/programming-processing/

  - курс: Подготовка к экзаменам
    направление: Экзамены
    диапазон возраста: от 15 до 18 лет
    описание: >
      Подготовка к ОГЭ (9 класс) и ЕГЭ (10–11 классы) по информатике.
    ссылка: https://it-schools.org/year/course/exam/

  - курс: Технология программирования
    направление: программирование
    диапазон возраста:  от 13 до 18 лет
    описание: >
      Изучение классических алгоритмов и методов решения задач.
      Обучение проходит 2 курса.
    ссылка: https://it-schools.org/year/course/programming-technology/
