курсы:
  - название: Курсы для дошкольников
    направление: дошкольное
    мин_возраст: 3
    макс_возраст: 7
    описание: >
      Занятия направлены на формирование познавательного интереса,
      памяти, внимания, интеллекта.
    ссылка: https://it-schools.org/year/course/preschool/

  - название: Робототехника
    направление: Робототехника
    мин_возраст: 7
    макс_возраст: 16
    описание: >
      На уроках робототехники в нашей школе дети осваивают базовую механику,
      основы электроники и программирования микропроцессоров.
      Обучение проходит 5 курсов.
    ссылка: https://it-schools.org/year/course/robotics/

  - название: Информатика для школы
    направление: Информатика
    мин_возраст: 8
    макс_возраст: 16
    описание: >
      На этом курсе обучающиеся изучают устройство компьютера,
      базовое программное обеспечение, основы работы с компьютером.
    ссылка: https://it-schools.org/year/course/informatics/

  - название: Теория информатики
    направление: Информатика
    мин_возраст: 10
    макс_возраст: 16
    описание: >
      Изучение теории по дисциплине «Информатика» и решение большого
      количества задач. Запись возможна только после прохождения
      первого курса Python или C++.
    ссылка: https://it-schools.org/year/course/theory-Informatics/

  - название: Спортивное программирование
    направление: программирование
    мин_возраст: 12
    макс_возраст: 15
    описание: >
      Основы программирования через соревновательную деятельность.
      Обучение проходит 3 курса.
    ссылка: https://it-schools.org/year/course/sport-prog/

  - название: Основы программирования
    направление: программирование
    мин_возраст: 9
    макс_возраст: 12
    описание: >
      Изучение базовых принципов алгоритмизации и развитие логического
      мышления. Обучение проходит 2 курса.
    ссылка: https://it-schools.org/year/course/programming-begin/

  - название: WEB-разработка
    направление: Web
    мин_возраст: 9
    макс_возраст: 17
    описание: >
      Изучение вёрстки сайтов и сопутствующих технологий.
      Обучение проходит 4 курса, есть возможность закрыть экстерном.
    ссылка: https://it-schools.org/year/course/web/

  - название: Компьютерная графика
    направление: Дизайн
    мин_возраст: 8
    макс_возраст: 17
    описание: >
      Работа с разными типами графики: векторная, растровая и трёхмерная.
      Обучение проходит 5 курсов.
    ссылка: https://it-schools.org/year/course/graphics/

  - название: Программирование Python
    направление: программирование
    мин_возраст: 9
    макс_возраст: 18
    описание: >
      Изучение языка Python: от лёгких приложений до ООП
      и работы с базами данных. Обучение проходит 4 курса.
    ссылка: https://it-schools.org/year/course/programming-python/

  - название: Программирование C++
    направление: программирование
    мин_возраст: 10
    макс_возраст: 18
    описание: >
      Изучение языка C++: от простых приложений до создания
      мессенджеров и онлайн-игр. Обучение проходит 4 курса.
    ссылка: https://it-schools.org/year/course/programming-cpp/

  - название: Нейронные сети
    направление: программирование
    мин_возраст: 14
    макс_возраст: 18
    описание: >
      Изучение основ нейронных сетей и их применения.
      Обучение проходит 2 курса.
    ссылка: https://it-schools.org/year/course/neuron/

  - название: Программирование Processing
    направление: программирование
    мин_возраст: 12
    макс_возраст: 18
    описание: >
      Изучение основ инструмента processing,
      создание с помощью него собственной игры.
    ссылка: https://it-schools.org/year/course/programming-processing/

  - название: Подготовка к экзаменам
    направление: Экзамены
    мин_возраст: 15
    макс_возраст: 18
    описание: >
      Подготовка к ОГЭ (9 класс) и ЕГЭ (10–11 классы) по информатике.
    ссылка: https://it-schools.org/year/course/exam/

  - название: Технология программирования
    направление: программирование
    мин_возраст: 13
    макс_возраст: 18
    описание: >
      Изучение классических алгоритмов и методов решения задач.
      Обучение проходит 2 курса.
    ссылка: https://it-schools.org/year/course/programming-technology/
