courses:
  - title: Курсы для дошкольников
    min_age: 3
    max_age: 7
    description: >
      Занятия направлены на формирование познавательного интереса,
      памяти, внимания, интеллекта.
    url: https://it-schools.org/year/course/preschool/

  - title: Робототехника
    min_age: 7
    max_age: 16
    description: >
      На уроках робототехники в нашей школе дети осваивают базовую механику,
      основы электроники и программирования микропроцессоров.
      Обучение проходит 5 курсов.
    url: https://it-schools.org/year/course/robotics/

  - title: Информатика для школы
    min_age: 8
    max_age: 16
    description: >
      На этом курсе обучающиеся изучают устройство компьютера,
      базовое программное обеспечение, основы работы с компьютером.
    url: https://it-schools.org/year/course/informatics/

  - title: Теория информатики
    min_age: 10
    max_age: 16
    description: >
      Изучение теории по дисциплине «Информатика» и решение большого
      количества задач. Запись возможна только после прохождения
      первого курса Python или C++.
    url: https://it-schools.org/year/course/theory-Informatics/

  - title: Спортивное программирование
    min_age: 12
    max_age: 15
    description: >
      Основы программирования через соревновательную деятельность.
      Обучение проходит 3 курса.
    url: https://it-schools.org/year/course/sport-prog/

  - title: Основы программирования
    min_age: 9
    max_age: 12
    description: >
      Изучение базовых принципов алгоритмизации и развитие логического
      мышления. Обучение проходит 2 курса.
    url: https://it-schools.org/year/course/programming-begin/

  - title: WEB-разработка
    min_age: 9
    max_age: 17
    description: >
      Изучение вёрстки сайтов и сопутствующих технологий.
      Обучение проходит 4 курса, есть возможность закрыть экстерном.
    url: https://it-schools.org/year/course/web/

  - title: Компьютерная графика
    min_age: 8
    max_age: 17
    description: >
      Работа с разными типами графики: векторная, растровая и трёхмерная.
      Обучение проходит 5 курсов.
    url: https://it-schools.org/year/course/graphics/

  - title: Программирование Python
    min_age: 9
    max_age: 18
    description: >
      Изучение языка Python: от лёгких приложений до ООП
      и работы с базами данных. Обучение проходит 4 курса.
    url: https://it-schools.org/year/course/programming-python/

  - title: Программирование C++
    min_age: 10
    max_age: 18
    description: >
      Изучение языка C++: от простых приложений до создания
      мессенджеров и онлайн-игр. Обучение проходит 4 курса.
    url: https://it-schools.org/year/course/programming-cpp/

  - title: Нейронные сети
    min_age: 14
    max_age: 18
    description: >
      Изучение основ нейронных сетей и их применения.
      Обучение проходит 2 курса.
    url: https://it-schools.org/year/course/neuron/

  - title: Программирование Processing
    min_age: 12
    max_age: 18
    description: >
      Изучение основ инструмента processing,
      создание с помощью него собственной игры.
    url: https://it-schools.org/year/course/programming-processing/

  - title: Подготовка к экзаменам
    min_age: 15
    max_age: 18
    description: >
      Подготовка к ОГЭ (9 класс) и ЕГЭ (10–11 классы) по информатике.
    url: https://it-schools.org/year/course/exam/

  - title: Технология программирования
    min_age: 13
    max_age: 18
    description: >
      Изучение классических алгоритмов и методов решения задач.
      Обучение проходит 2 курса.
    url: https://it-schools.org/year/course/programming-technology/
