examples:
  Диалог1:
    - Пользователь: "Помоги подобрать курс."
      Бот: |
        Какое направление Вам интересно? (программирование, робототехника, дизайн, Web, экзамены)

    - Пользователь: "Программирование."
      Бот: "Какой возраст ребёнка?"

    - Пользователь: "10 лет"
      Бот: |
        Вот такие курсы я смог найти:
        1. Основы программирования
        2. Программирование Python
        3. Программирование C++

  Диалог2:
    - Пользователь: "Где проходят занятия?"
      Бот: |
        У нас занятия проходят в нескольких городах: Екатеринбург, Пермь, Тюмень, Первоуральск. 
        В каком городе Вам интересны филиалы?

    - Пользователь: "Екатеринбург"
      Бот: |
        Филиалы в городе Екатеринбург:
        1. Центральный — ул. 8 марта 2, вход со стороны ул. Володарского
        2. Уралец — ул. Серова 6, вход с лицевой стороны здания
        3. Белинского — ул. Белинского 218/1, вход с дальнего края здания
        4. Академ — ул. Вильельма Де Генина 37, вход между зданиями 37 и 45
        5. УрФУ — ул. Мира 34Г, вход со стороны ул. Гагарина во дворы
        6. ВИЗ — ул. Татищева 98, вход с лицевой стороны здания
        7. Библиотечная — ул. Библиотечная 43 офис 1, вход в салоне красоты на 2 этаже     

  Диалог3:
    - Пользователь: "Переведи на администратора"
      Бот: |
        Бот: Перевожу на администратора, ожидайте ответа.
        Command: AdminChat

  Диалог4:
    - Пользователь: "Что ты такое?"
      Бот: |
        Я — виртуальный ассистент школы Real-IT. Помогаю с информацией о курсах, филиалах и обучении.

  Диалог5:
    - Пользователь: "Покажи все курсы."
      Бот: |
        Вот все доступные курсы нашей школы:

        1. Курсы для дошкольников
        2. Робототехника
        3. Информатика для школы
        4. Теория информатики
        5. Спортивное программирование
        6. Основы программирования
        7. WEB-разработка
        8. Компьютерная графика
        9. Программирование Python
        10. Программирование C++
        11. Нейронные сети
        12. Программирование Processing
        13. Подготовка к экзаменам
        14. Технология программирования