Екатеринбург:
  - title: Центральный
    street: ул.8 марта 2
    entrance: Вход со стороны ул.Володарского
    url: https://it-schools.org/img/maps/map12.jpg

  - title: Уралец
    street: ул.Серова 6
    entrance: Вход находится с лицевой стороны здания
    url: https://it-schools.org/img/maps/map16.jpg

  - title: Белинского
    street: ул.Белинского 218/1
    entrance: Вход с дальнего края здания
    url: https://it-schools.org/img/maps/map15.jpg

  - title: Академ
    street: ул.Вильельма Де Генина 37
    entrance: Вход находится между зданием 37 и 45
    url: https://it-schools.org/img/maps/map17.jpg

  - title: УрФУ
    street: ул.Мира 34Г
    entrance: Вход со стороны ул.Гагарина во дворы
    url: https://it-schools.org/img/maps/map11.jpg

  - title: ВИЗ
    street: ул.Татищева 98
    entrance: Вход находится с лицевой стороны здания
    url: https://it-schools.org/img/maps/map13.jpg

  - title: Библиотечная
    street: ул.Библиотечная 43 офис 1, домофон 1
    entrance: Вход находится в салоне красоты на 2 этаже
    url: https://it-schools.org/img/maps/map14.jpg

Пермь:
  - title: Мотовилиха
    street: ул. Тургенева 33а
    entrance: Отдельный вход со стороны ул. Тургенева
    url: https://it-schools.org/img/maps/map41.jpg
  
  - title: Индустриальный
    street: ул.Мира 67
    entrance: Вход со стороны ул.Космонавта Леонова
    url: https://it-schools.org/img/maps/map42.jpg

Первоуральск:
  - title: Ватутина
    street: ул.Ватутина 57 офис 304, домофон Real-IT
    entrance: Вход правее от Сбербанка
    url: https://it-schools.org/img/maps/map23.jpg
  
Тюмень:
  - title: Гудвин
    street: ул.Фабричная 1
    entrance: Вход со стороны ул. Максима Горького
    url: https://it-schools.org/img/maps/map51.jpg
  
  - title: Пермякова
    street: ул.Пермякова 21
    entrance: Вход со стороны остановки Улица Пермякова
    url: https://it-schools.org/img/maps/map52.jpg