Екатеринбург:
  - название: Центральный
    улица: ул.8 марта 2
    вход: со стороны ул.Володарского

  - название: Уралец
    улица: ул.Серова 6
    вход: находится с лицевой стороны здания

  - название: Белинского
    улица: ул.Белинского 218/1
    вход: с дальнего края здания

  - название: Академ
    улица: ул.Вильельма Де Генина 37
    вход: находится между зданием 37 и 45

  - название: УрФУ
    улица: ул.Мира 34Г
    вход: со стороны ул.Гагарина во дворы

  - название: ВИЗ
    улица: ул.Татищева 98
    вход: находится с лицевой стороны здания

  - название: Библиотечная
    улица: ул.Библиотечная 43 офис 1, домофон 1
    вход: находится в салоне красоты на 2 этаже

Пермь:
  - название: Мотовилиха
    улица: ул.Тургенева 33а
    вход: Отдельный вход со стороны ул.Тургенева

  - название: Индустриальный
    улица: ул.Мира 67
    вход: со стороны ул.Космонавта Леонова

Первоуральск:
  - название: Ватутина
    улица: ул.Ватутина 57 офис 304, домофон Real-IT
    вход: правее от Сбербанка
  
Тюмень:
  - название: Гудвин
    улица: ул.Фабричная 1
    вход: со стороны ул.Максима Горького
  
  - название: Пермякова
    улица: ул.Пермякова 21
    вход: со стороны остановки Улица Пермякова
