преподаватели:
  - ФИО: Филатов Данил Александрович
    описание: |
      Образование: Высшее
          Российский Государственный Профессионально-педагогический университет
          Специализация: Информационные (компьютерные) технологии
          Квалификация: Педагог профессионального обучения
  - ФИО: Кузнецов Николай Николаевич
    описание: |
      Образование: Высшее
          Уральский Федеральный Университет имени первого президента РФ Б.Н. Ельцина
          Факультет: Физико-технический
          Квалификация: Инженер-физик
