teachers:
  - id: Filatov
    name: Филатов Данил Александрович
    description: |
      Образование: Высшее
          Российский Государственный Профессионально-педагогический университет
          Специализация: Информационные (компьютерные) технологии
          Квалификация: Педагог профессионального обучения
      Образование: Средне-профессиональное
          Уральский государственный колледж имени А.С.Попова
          Специализация: Обслуживание средств вычислительной техники и компьютерных сетей
          Квалификация: Техник
      Педагогический стаж: 10 лет
      Практическая деятельность:
          Разработка методического материала по направлениям "Двумерные игры", "Веб-технологии экстерн"
          Опыт коммерческой разработки компьютерных игр
  - id: Kuznetsov
    name: Кузнецов Николай Николаевич
    description: |
      Образование: Высшее
          Уральский Федеральный Университет имени первого президента РФ Б.Н. Ельцина
          Факультет: Физико-технический
          Квалификация: Инженер-физик
      Педагогический стаж: Более 10 лет
      Практическая деятельность:
          Разработка методического материала по направлениям "Компьютерная графика-4", "Компьютерная графика-5", "Робототехника-4"
